# Generated by Django 3.0.8 on 2021-05-31 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_album_author_book_car_song_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRDTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.CharField(max_length=1000, null=True)),
                ('recovered', models.CharField(max_length=1000, null=True)),
                ('deceased', models.CharField(max_length=1000, null=True)),
                ('tested', models.CharField(max_length=1000, null=True)),
                ('vaccinated', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CRDTV')),
            ],
        ),
        migrations.CreateModel(
            name='Delta7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CRDTV')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1000)),
                ('dates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dates')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CRDTV')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.AddField(
            model_name='dates',
            name='delta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Delta'),
        ),
        migrations.AddField(
            model_name='dates',
            name='delta7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Delta7'),
        ),
        migrations.AddField(
            model_name='dates',
            name='total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Total'),
        ),
    ]
