# Generated by Django 3.0.8 on 2021-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210531_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseries',
            name='dates',
        ),
        migrations.AddField(
            model_name='timeseries',
            name='dates',
            field=models.ManyToManyField(to='api.Dates'),
        ),
    ]
