# Generated by Django 3.0.8 on 2021-06-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210601_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='dates',
            field=models.ManyToManyField(related_name='state_date', to='api.Dates'),
        ),
    ]
